on:
  schedule:
      # Runs every hour
      - cron: '0 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://fabioo29-devfolio.herokuapp.com/"
